import logging
import os
import re
import subprocess
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import Optional

from ..config import Profile
from .networking import delete_vm_network, setup_vm_network, start_dnsmasq, stop_dnsmasq
from .storage import get_storage_backend

log = logging.getLogger(__name__)

FIRST_CDROM_DRIVE = "hdc"
SECOND_CDROM_DRIVE = "hdd"


class VMError(RuntimeError):
    def __init__(self, message: str, vm_name: str, with_qemu_logs: bool = True):
        self.vm_name = vm_name
        if with_qemu_logs:
            log_path = Path(f"/var/log/xen/qemu-dm-{vm_name}.log")
            try:
                message += f"\n---- {str(log_path)}:\n{log_path.read_text()}"
            except Exception:
                log.warning("Failed to read qemu log for additional details")
        super().__init__(message)


class VirtualMachine:
    def __init__(self, profile: Profile, vm_id: int):
        self.profile = profile
        self.storage = get_storage_backend(self.profile)
        self.vm_id = vm_id
        self.vm_name = profile.get_vm_name(vm_id)

    @property
    def is_running(self) -> bool:
        res = subprocess.run(
            ["xl", "list", self.vm_name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return res.returncode == 0

    @property
    def snapshot_path(self) -> Path:
        return self.profile.volumes_dir / "snapshot.sav"

    @property
    def vm_config_path(self) -> Path:
        return self.profile.vm_config_dir / f"vm-{self.vm_id}.cfg"

    def make_vm_config(
        self, first_cd: Optional[Path] = None, second_cd: Optional[Path] = None
    ) -> Path:
        """
        Creates configuration from template and ensures its existence
        """
        template = self.profile.vm_template_path.read_text()

        disks = [self.storage.get_vm_disk_path(self.vm_id)]

        if first_cd:
            disks.append(f"file:{str(first_cd.resolve())},{FIRST_CDROM_DRIVE}:cdrom,r")

        if second_cd:
            disks.append(
                f"file:{str(second_cd.resolve())},{SECOND_CDROM_DRIVE}:cdrom,r"
            )

        install_info = self.profile.install_info
        vm_name = self.vm_name
        vm_id = self.vm_id
        disks_spec = ", ".join(['"{}"'.format(disk) for disk in disks])

        template = template.replace("{{ VM_NAME }}", str(vm_name))
        template = template.replace("{{ VM_ID }}", str(vm_id))
        template = template.replace("{{ DISKS }}", disks_spec)
        template = template.replace("{{ VNC_PORT }}", str(6400 + vm_id))
        template = template.replace("{{ VCPUS }}", str(install_info.vcpus))
        template = template.replace("{{ MEMORY }}", str(install_info.memory))

        # Never destroy vm-0 on reboot, it's installation VM
        # In other cases: VM profiles no longer match vm-0 state after reboot
        # so vm-N should be destroyed (unless user wants different behavior)
        if vm_id == 0:
            template = re.sub("on_reboot[ ]*=(.*)", 'on_reboot = "restart"', template)

        vm_config_path = self.vm_config_path
        with vm_config_path.open("w") as f:
            f.write("# Autogenerated, don't edit this file directly!\n")
            f.write("# Instead please edit /etc/drakrun/scripts/cfg.template\n")
            f.write("# and restart drakrun@<vm_id> service.\n\n")
            f.write(template)

        log.info(f"Generated VM configuration for vm-{vm_id}")
        return vm_config_path

    def setup_network(self, out_interface: str, dns_server: str, net_enable: bool):
        setup_vm_network(self.vm_name, out_interface, dns_server, net_enable)
        if net_enable:
            start_dnsmasq(self.vm_name, dns_server, background=True)

    def clean_network(self):
        stop_dnsmasq(self.vm_name)
        delete_vm_network(self.vm_name)

    def create(
        self,
        paused=True,
        first_cd: Optional[Path] = None,
        second_cd: Optional[Path] = None,
    ):
        if self.vm_id == 0:
            raise RuntimeError("This method can't be used for VMs other than vm-0")
        vm_config_path = self.make_vm_config(first_cd, second_cd)
        args = ["xl", "create"]
        if paused:
            args += ["-p"]
        args += [str(vm_config_path)]
        log.info(f"Creating VM {self.vm_name}")
        try:
            subprocess.run(
                args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True
            )
        except subprocess.CalledProcessError as e:
            raise VMError(f"Failed to launch VM {self.vm_name}", vm_name=self.vm_name)

    def pause(self):
        try:
            subprocess.run(
                ["xl", "pause", self.vm_name],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=True,
            )
        except subprocess.CalledProcessError as e:
            raise VMError(f"Failed to pause VM {self.vm_name}", vm_name=self.vm_name)

    def unpause(self):
        try:
            subprocess.run(
                ["xl", "unpause", self.vm_name],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=True,
            )
        except subprocess.CalledProcessError as e:
            raise VMError(f"Failed to unpause VM {self.vm_name}", vm_name=self.vm_name)

    def save(self):
        if self.vm_id == 0:
            raise RuntimeError("This method can't be used for VMs other than vm-0")

        logging.info(f"Saving VM {self.vm_name}")
        try:
            # We want to keep it running after saving
            subprocess.run(
                ["xl", "save", "-c", self.vm_name, str(self.snapshot_path)],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=True,
            )
        except subprocess.CalledProcessError as e:
            raise VMError(f"Failed to save VM {self.vm_name}", vm_name=self.vm_name)

    def restore(self, paused=False):
        if self.is_running:
            self.destroy()
        vm_config_path = self.make_vm_config()
        args = ["xl", "restore"]
        if paused is True:
            args += ["-p"]
        # No need to rollback storage for vm-0.
        # The state of vm-0 is correct by definition.
        if self.vm_id != 0:
            self.storage.rollback_vm_storage(self.vm_id)
        args += [str(self.vm_config_path), str(self.snapshot_path)]
        logging.info(f"Restoring VM {self.vm_name}")
        try:
            # We want to keep it running after saving
            subprocess.run(
                args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True
            )
        except subprocess.CalledProcessError as e:
            raise VMError(f"Failed to restore VM {self.vm_name}", vm_name=self.vm_name)

    def destroy(self):
        try:
            subprocess.run(
                ["xl", "destroy", self.vm_name],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=True,
            )
        except subprocess.CalledProcessError as e:
            raise VMError(f"Failed to destroy VM {self.vm_name}", vm_name=self.vm_name)

    @contextmanager
    def run_vm(self):
        """
        High-level method that restores a clean VM from snapshot
        and ensures that it is destroyed after operation
        """
        self.restore()
        try:
            yield self
        finally:
            self.destroy()


def make_unattended_iso(xml_path, iso_path):
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_xml_path = os.path.join(tmpdir, "autounattend.xml")

        with open(tmp_xml_path, "wb") as fw:
            with open(xml_path, "rb") as fr:
                fw.write(fr.read())

        try:
            subprocess.check_output(
                [
                    "genisoimage",
                    "-o",
                    iso_path,
                    "-J",
                    "-r",
                    tmp_xml_path,
                ],
                stderr=subprocess.STDOUT,
            )
        except subprocess.CalledProcessError:
            logging.exception("Failed to generate unattended.iso.")
